### ISSUE TITLE
How to distribute?

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/async-tokio#12]
should we provide python module with `async-tokio`? at the moment async-tokio is rust crate, to run event loop aiohttp-tokio is required.

**Comment by 1st1** [comment]
We'll definitely need a PyPI package with wheels.

**Comment by fafhrd91** [comment]
Inititaly async-tokio had setup.py, I removed it because I thought maybe asyncio-core should be just library, and other developers can build spesialized version of it for their needs. But that's probably too early. Also making asyncio-tokio package would make it easier for new developers to start hacking on it

setuptools-rust can build wheel

**Comment by fafhrd91** [comment]
added "setup.py" and "setuptools-rust".

@1st1 do you think we should add proper python package? now it is just tokio.so

**Comment by 1st1** [comment]
> @1st1 do you think we should add proper python package? now it is just tokio.so

Yes, we'll essentially need a copy of https://github.com/MagicStack/uvloop/blob/master/uvloop/__init__.py.

**Comment by fafhrd91** [comment]
async-tokio has been converted to standalone package
